#!/usr/bin/env bash
# Assessment section 6.4 step 10 (D's P0 steps 6-8) for Procedures A2 and B: one hand start of the
# Duplicati server that sets a KNOWN web-UI password on the placed database, then exits.
#
# Project:    juniper-ml
# Sub-Project: ad-hoc tooling
# Author:     Paul Calnon
# Created:    2026-10-03
# Version:    1.3.0 (2026-10-08: Phase B round-4 fold-in -- see HISTORY)
# Status:     ad-hoc -- recovery (the assessment's B10; issues I-19, I-37)
# Retire when: RETAINED -- ad-hoc scripts are kept as provenance of record (owner policy 2026-08-25)
# Related:    notes/JUNIPER_2026-10-03_JUNIPER-ECOSYSTEM_BACKUP-SYSTEM-STATE-ASSESSMENT-AND-RECOVERY-PLAN.md
#             section 6.4 steps 0 and 10; notes/JUNIPER_2026-09-21_...INTEGRATED-DESIGN.md section 8 P0
#
# WHY THIS EXISTS. Procedure A2's `wipe-encryption` clears `pbkdf-config`, the ONLY home of the
# web-UI password since Duplicati 2.1 (validation Lane B B-1, confirmed in the 2.4.0.0 source:
# Connection.PasswordFieldNames includes it, WipeEncryption clears it, VerifyWebserverPassword
# returns false on an empty config). Procedure B starts from an empty database. In both cases
# the server's next start mints a RANDOM password (`UpgradePasswordToKBDF`, autogenerated=True),
# and because `--webservice-disable-signin-tokens` is applied unconditionally at every start
# (Server/Program.cs line 662), no signin token is accepted either -- the recovered server would
# be unreachable. This script runs the server ONCE, by hand, with `--webservice-password-init`,
# which sets the password and makes the server exit 102 (EXITCODE_INITPASSWORD_SUCCESS).
#
# WHAT THAT RUN DOES AND DOES NOT DO (Server/Program.cs, 2.4.0.0; Phase B validation, lanes A/B).
# The 102 return happens inside AdjustApplicationSettings (line 682), which Main reaches at line
# 286 -- BEFORE the web server is started (295) and BEFORE ReWriteAllFieldsIfEncryptionChanged
# (324), the only writer of `encrypted-fields`. So after exit 102: the schema is upgraded
# (Program.cs 1148), FixInvalidBackupId has run (262-263), the password is set (`pbkdf-config` is an
# `enc-v1:` blob under the settings key), `autogenerated-passphrase` is False, and SaveSettings has
# re-encrypted EVERY password-named server setting under the settings key (ServerSettings.cs 209-218,
# Connection.cs 1585-1590) -- not only the password (round 3, R3A N-3). The backups' own fields
# (TargetURL, Source paths, job options) are still as placed, and `encrypted-fields` is still False
# (or absent). The full re-encryption happens
# at the UNIT'S FIRST START, which does reach line 324. Verify `encrypted-fields=True` THERE
# (assessment step 13), never after this run. No socket is bound on the 102 path either: the
# interface/port/hostnames options below are passed for safety and are inert.
# Exit 200 means another server instance holds the single-instance lock (Program.cs 949/960):
# the unit is still running -- stop it first.
#
# Procedure A0 does NOT use this: its restored database already has a real password, and on such
# a database the option returns 103 and changes nothing.
#
# SECRETS. Both values are read from 0600 files and delivered through `--parameters-file`, a
# 0600 file the server reads in-process (Program.cs ReadOptionsFromFile). Nothing secret goes
# on argv (world-readable via /proc/*/cmdline) or into the environment of a child. The
# parameters file is shredded on exit, success or failure.
#
# Usage (as root, with the data folder placed and 0700 duplicati:duplicati, the unit NOT running,
# and nothing listening on PORT):
#   sudo bash util/ad-hoc/2026-10-03_password_init_hand_start.bash \
#        --data-folder /home/duplicati/.config/Duplicati \
#        --settings-key-file /etc/credstore/duplicati-settings-key \
#        --ui-password-file /root/.ui-password.new \
#        [--port 8399] [--dry-run]
# The UI-password file: create it without the value touching the shell history, and shred it
# after assessment step 11 has changed the password through the UI --
#   (set +o history; umask 077; read -rs -p 'new UI password: ' p; printf '%s\n' "$p" > /root/.ui-password.new)
#   ... later: shred -u /root/.ui-password.new
# Rehearse it first on a throwaway folder (assessment section 6.4 step 0) with an empty database
# and a THROWAWAY key file (the real key does not exist until step 9).
#
# HISTORY
#   1.0.0  2026-10-03  first version (the assessment's B10).
#   1.1.0  2026-10-03  Phase B validation fold-in: the 102 run sets the password only -- the
#                      encryption claim and the verification it prescribed were wrong (lanes A/B);
#                      port gate fails closed (ss output captured, `ss` required); edge whitespace in a
#                      secret refused (the server trims parameters-file lines); exit 200 named.
#   1.2.0  2026-10-08  round-3 fold-in: the secret-format gate (one line, no edge whitespace, no CR) runs
#                      under --dry-run too, so "gates passed" is true (R3C N-1); a CR in a secret file
#                      refused (R3C N-2); the header names everything the 102 run writes and the log
#                      line no longer claims a listener (R3A N-3).
#   1.3.0  2026-10-08  round-4 fold-in: a NUL in a secret file refused (R4C NIT-6).
set -euo pipefail

DATA_FOLDER=""
KEY_FILE=""
PW_FILE=""
PORT=8399
DRY_RUN=0
SERVER="${DUPLICATI_SERVER:-/usr/bin/duplicati-server}"
RUN_AS="${DUPLICATI_RUN_AS:-duplicati}"

usage() {
    cat >&2 <<'USAGE'
usage: sudo bash util/ad-hoc/2026-10-03_password_init_hand_start.bash \
         --data-folder <folder> --settings-key-file <0600 file> --ui-password-file <0600 file> [--port 8399] [--dry-run]
One hand start that sets a known web-UI password on the placed database; expects exit 102.
Procedures A2 and B only -- a database with a real password (A0) returns 103 and changes nothing.
The unit's FIRST START is what encrypts the rest of the database (verify encrypted-fields there).
USAGE
    exit 2
}
while (( $# )); do
    case "$1" in
        --data-folder) DATA_FOLDER="${2:?}"; shift 2 ;;
        --settings-key-file) KEY_FILE="${2:?}"; shift 2 ;;
        --ui-password-file) PW_FILE="${2:?}"; shift 2 ;;
        --port) PORT="${2:?}"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        *) echo "unknown argument: $1" >&2; usage ;;
    esac
done
[[ -n "${DATA_FOLDER}" && -n "${KEY_FILE}" && -n "${PW_FILE}" ]] || usage

log() { printf '%s: %s\n' "${0##*/}" "$*" >&2; }
die() { log "FATAL: $*"; exit 1; }

# Gates, all before anything is written -- and all of them run under --dry-run too (round 3, R3C N-1:
# the secret-format gate used to run only on the real path, so a dry run said "gates passed" about a
# secret the real run then refused).
[[ -d "${DATA_FOLDER}" ]] || die "data folder missing: ${DATA_FOLDER}"
[[ "$(stat -c '%U:%a' "${DATA_FOLDER}")" == "${RUN_AS}:700" ]] || die "data folder must be ${RUN_AS}-owned mode 0700 (the server refuses anything else): $(stat -c '%U:%a' "${DATA_FOLDER}")"
for f in "${KEY_FILE}" "${PW_FILE}"; do
    [[ -s "${f}" ]] || die "secret file missing or empty: ${f}"
    [[ "$(stat -c '%a' "${f}")" == "600" ]] || die "secret file must be mode 0600, never readable by the group: ${f} is $(stat -c '%a' "${f}")"
done
# The port gate fails CLOSED: the listener list is captured first (a `ss | grep -q` pipeline under
# pipefail reports 141 once grep closes early, which read as "free"), and a host without `ss` is
# refused rather than assumed free.
command -v ss >/dev/null 2>&1 || die "ss not found; cannot prove port ${PORT} is free"
LISTENING="$(ss -ltn 2>/dev/null || true)"
if grep -qE "[:.]${PORT}\s" <<< "${LISTENING}"; then
    die "port ${PORT} is in use; pick an unused loopback port with --port"
fi
# Root is needed only to run the server as ANOTHER user (sudo -u). A rehearsal as the current user
# (DUPLICATI_RUN_AS=$(id -un), a throwaway 0700 folder, a stub server) needs neither.
SAME_USER=0
[[ "${RUN_AS}" == "$(id -un)" ]] && SAME_USER=1
if (( DRY_RUN == 0 )); then
    (( SAME_USER )) || [[ "$(id -u)" -eq 0 ]] || die "run with sudo (or --dry-run to rehearse the gates)"
    [[ -x "${SERVER}" ]] || die "server binary not executable: ${SERVER}"
    id -u "${RUN_AS}" >/dev/null 2>&1 || die "no such user: ${RUN_AS}"
fi

# The parameters file: one option per line, read by the server in-process. Values are read from
# the files with python so that a value holding $ & # @ or a quote survives verbatim -- a bash
# `read` or `cat` into an unquoted word does not (the credential files on this host carry all of
# them; design section 6, "a credential file may not be dot-sourceable").
# It lives INSIDE the data folder (0700, owned by the service user), because the server runs as
# that user and could not traverse /root to read it; the folder's 0700 gate checks the folder's
# own mode, not its contents.
PARAMS="$(mktemp -u "${DATA_FOLDER}/.password-init-XXXXXX")"
cleanup() {
    if [[ -e "${PARAMS}" ]]; then
        shred -u "${PARAMS}" 2>/dev/null || rm -f "${PARAMS}"
        log "parameters file shredded"
    fi
}
trap cleanup EXIT

# The secret-format gate, and (given a path) the parameters file. Values are never printed. A file is
# read WITHOUT newline translation: a CR would reach the server as part of the key through the unit
# (the wrapper keeps it) but not through this file (round 3, R3C N-2), so it is refused.
write_params() {
    python3 - "${KEY_FILE}" "${PW_FILE}" "$1" <<'PY'
import sys
def read(path):
    with open(path, encoding="utf-8", newline="") as fh:
        return fh.read().rstrip("\n")
key, pw = read(sys.argv[1]), read(sys.argv[2])
if not key or not pw or "\n" in key or "\n" in pw:
    sys.exit("FATAL: each secret file must hold exactly one non-empty line")
if "\r" in key or "\r" in pw:
    sys.exit("FATAL: a secret file holds a carriage return -- the unit would deliver a different key than this run")
if "\0" in key or "\0" in pw:
    sys.exit("FATAL: a secret file holds a NUL byte -- the wrapper drops it, so the unit would deliver a different key than this run")
if key != key.strip() or pw != pw.strip():
    sys.exit("FATAL: a secret must not begin or end with whitespace -- the server trims every parameters-file line, so it would not survive verbatim")
if sys.argv[3]:
    with open(sys.argv[3], "w", encoding="utf-8") as fh:
        fh.write(f"--settings-encryption-key={key}\n--webservice-password-init={pw}\n")
PY
}
write_params ""

if (( DRY_RUN )); then
    log "dry run: gates passed; would write a 0600 parameters file carrying --settings-encryption-key and --webservice-password-init (values from ${KEY_FILE} and ${PW_FILE}, never printed), then run:"
    log "  ${SERVER} --server-datafolder=${DATA_FOLDER} --parameters-file=<file> --webservice-interface=loopback --webservice-port=${PORT} --webservice-allowed-hostnames=localhost  (as ${RUN_AS})"
    log "  expecting exit 102 (password set; the unit's first start encrypts the rest) -- 103 means the database already had a real password (Procedure A0: do not use this script); 200 means a server instance is still running"
    exit 0
fi

umask 077
write_params "${PARAMS}"
(( SAME_USER )) || chown "${RUN_AS}:${RUN_AS}" "${PARAMS}"
chmod 0600 "${PARAMS}"
log "running the server once as ${RUN_AS} with --webservice-port=${PORT}, inert on the 102 path: no socket is bound (parameters file $(stat -c '%a' "${PARAMS}"), data folder ${DATA_FOLDER})"

AS_USER=(sudo -u "${RUN_AS}" --)
(( SAME_USER )) && AS_USER=()
set +e
"${AS_USER[@]}" "${SERVER}" \
    "--server-datafolder=${DATA_FOLDER}" \
    "--parameters-file=${PARAMS}" \
    --webservice-interface=loopback \
    "--webservice-port=${PORT}" \
    --webservice-allowed-hostnames=localhost
rc=$?
set -e
case "${rc}" in
    102) log "exit 102: UI password set. On a COPY (copy the -wal/-shm siblings too -- this run does not dispose its connection): autogenerated-passphrase=False, pbkdf-config an enc-v1: blob under the settings key, encrypted-fields still False. The unit's first start encrypts every other field; verify encrypted-fields=True after THAT (assessment step 13)." ;;
    103) die "exit 103: the database already carries a real password, so --webservice-password-init changed nothing. This is the Procedure A0 case; set the password through the UI after the unit's first start instead." ;;
    200) die "exit 200: another server instance holds the single-instance lock (the unit is running?) -- stop it, then retry. The parameters file is shredded." ;;
    *)   die "unexpected exit ${rc}; read the journal/stderr above. The parameters file is shredded." ;;
esac
