#!/usr/bin/env python3
"""Extract Duplicati's SERVER option table (names and aliases) from its source, for a test fixture.

Project:     juniper-ml
Sub-Project: backup infrastructure
Author:      Paul Calnon
Created:     2026-10-08
Version:     1.0.0
Status:      ad-hoc -- fixture generator (Phase B round-4 fold-in, lane C1; R4A D-2)
Retire when: RETAINED -- ad-hoc scripts are kept as provenance of record (owner policy 2026-08-25)
Related:     tests/fixtures/duplicati_2.4.0.0_server_options.txt (what it writes)
             tests/test_duplicati_wrapper_contract.py (WrapperEnvContract pins the wrapper's lists to it)

Usage:  c1_extract_server_options.py <dir-with-sources> > tests/fixtures/duplicati_2.4.0.0_server_options.txt

<dir-with-sources> holds these files, fetched read-only from github.com/duplicati/duplicati at tag
v2.4.0.0_stable_2026-09-03 (commit b3e9268c2c759e48f2077d17073476cbad44e59a), flat:
  Program.cs            Duplicati/Server/Program.cs         (SupportedCommands: the table itself)
  WebServerLoader.cs    Duplicati/Server/WebServerLoader.cs (OPTION_* constants)
  DataFolderManager.cs  Duplicati/Library/AutoUpdater/DataFolderManager.cs
  Util.cs               Duplicati/Library/Common/IO/Util.cs (AllowInsecureDatafolderOption)
  Options.cs            Duplicati/Library/Main/Options.cs   (the secret-provider* options the table splices in)

Why: 2.3.0's allow-list was hand-copied and carried `suppress-welcome-page`, a name the server does
not have (the real one is `webservice-suppress-welcome-page`), and the test pinned the same wrong
name. The fixture lets the suite check every allow/deny entry against the PRODUCT's table instead.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

FILES = ("Program.cs", "WebServerLoader.cs", "DataFolderManager.cs", "Util.cs", "Options.cs")


def main() -> int:
    src = Path(sys.argv[1])
    texts = {name: (src / name).read_text(encoding="utf-8") for name in FILES}
    consts: dict[str, str] = {}
    for name in ("Program.cs", "WebServerLoader.cs", "DataFolderManager.cs", "Util.cs"):
        for m in re.finditer(r'const string (\w+) = "([^"]+)"', texts[name]):
            consts[m.group(1)] = m.group(2)
    # Constants defined as another constant (ALLOW_INSECURE_DATAFOLDER_OPTION = Util.AllowInsecureDatafolderOption).
    for m in re.finditer(r"const string (\w+) = (?:\w+\.)?(\w+);", texts["DataFolderManager.cs"]):
        if m.group(2) in consts:
            consts[m.group(1)] = consts[m.group(2)]
    arrays = {m.group(1): re.findall(r'"([^"]+)"', m.group(2)) for m in re.finditer(r"string\[\] (\w+) = \[([^\]]*)\]", texts["Program.cs"])}

    prog = texts["Program.cs"]
    start = prog.index("WindowsOptions = ")
    table = prog[start:prog.index("KnownDuplicateOptions", start)]
    rows: list[tuple[str, list[str]]] = []
    for line in table.splitlines():
        m = re.search(r"new CommandLineArgument\((?:\w+\.)?(\w+),", line)
        if not m:
            continue
        name = consts[m.group(1)]
        aliases: list[str] = []
        for am in re.finditer(r"\[((?:\w+\.)?\w+_ALT)\]", line):
            aliases.append(consts[am.group(1).split(".")[-1]])
        for arr, values in arrays.items():
            if re.search(rf"\b{arr}\)", line):
                aliases.extend(values)
        rows.append((name, aliases))
    if ".. SECRET_PROVIDER_OPTIONS" not in table:
        sys.exit("the table no longer splices SECRET_PROVIDER_OPTIONS; re-read Program.cs")
    for name in sorted(set(re.findall(r'"(secret-provider[a-z-]*)"', texts["Options.cs"]))):
        rows.append((name, []))

    print("# Duplicati 2.4.0.0 SERVER options: one canonical name per line, aliases after it, space-separated.")
    print("# Source: github.com/duplicati/duplicati tag v2.4.0.0_stable_2026-09-03 (commit b3e9268c2c759e48f2077d17073476cbad44e59a),")
    print("# Program.cs SupportedCommands (+ WindowsOptions, + the secret-provider* options it splices in from Library/Main/Options.cs),")
    print("# names resolved from the OPTION_* constants. Fetched read-only 2026-10-08; generated by")
    print("# util/ad-hoc/2026-10-08_backup-phase-b-fold-in/c1_extract_server_options.py. Source file sha256:")
    for name in FILES:
        print(f"#   {hashlib.sha256((src / name).read_bytes()).hexdigest()}  {name}")
    print(f"# {len(rows)} options.")
    for name, aliases in rows:
        print(" ".join([name, *aliases]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
